In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
a= [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [ ]:
b = [1, 2, 3.5, 'hello']
b

[1, 2, 3.5, 'hello']

In [ ]:
np.array(b)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [ ]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#array generation

In [ ]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros((6,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(0, 2, 3)
arr

array([0., 1., 2.])

In [ ]:
#random generation functions

In [ ]:
arr = np.random.rand(4)
arr      #starting from 0 to 1

array([0.04795143, 0.87383216, 0.92041076, 0.36249489])

In [ ]:
arr = np.random.randn(4)
arr      #starting from -3 to 3

array([ 1.52738427, -0.17914898, -0.77540392, -0.69970265])

In [ ]:
arr = np.random.randint(0, 20, 10)
arr      #starting from 0 to 20

array([ 6,  5, 14,  0, 15,  9, 15,  0, 13,  0])

In [ ]:
#array attributes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#Array methods

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.sum(arr, axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
arr = np.arange(0, 30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr = arr.reshape(5, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
import numpy as np

In [ ]:
#numpy indexing and slicing of vectors

In [ ]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[0:4]

array([11, 12, 13, 14])

In [ ]:
arr[:4:2]

array([11, 13])

In [ ]:
arr_slice = arr[3::3]
arr_slice

array([14, 17, 20])

In [ ]:
arr[6]

np.int64(17)

In [ ]:
#numpy indexing and slicing of matrix

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
slice = arr[2:5,3:5]
slice

array([[14, 15],
       [19, 20],
       [24, 25]])

In [ ]:
slice = arr[1::2,2:]
slice

array([[ 8,  9, 10],
       [18, 19, 20]])

In [ ]:
arr[:,1::2]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19],
       [22, 24]])

In [ ]:
#Boolean Indexing

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
bool_index = arr% 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [ ]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#