In [ ]:
import numpy as np

In [ ]:
#valid sudoku

In [ ]:
s = np.array([
[5, 3, 4, 6, 7, 8, 9, 1, 2],
[6, 7, 2, 1, 9, 5, 3, 4, 8],
[1, 9, 8, 3, 4, 2, 5, 6, 7],

[8, 5, 9, 7, 6, 1, 4, 2, 3],
[4, 2, 6, 8, 5, 3, 7, 9, 1],
[7, 1, 3, 9, 2, 4, 8, 5, 6],

[9, 6, 1, 5, 3, 7, 2, 8, 4],
[2, 8, 7, 4, 1, 9, 6, 3, 5],
[3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
b = np.sum(s,axis= 1)
for i in b:
  if i != 45:
    print("sudoku is not valid")
    break
else:
    print("sudoku is vaid")

sudoku is vaid


In [ ]:
c = np.sum(s,axis= 0)
for i in b:
  if i != 45:
    print("sudoku is not valid")
    break
else:
    print("sudoku is vaid")

sudoku is vaid


In [ ]:
s[0:3, 0:3]    #slicing

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [ ]:
s[3:6, 6:9]    #slicing

array([[4, 2, 3],
       [7, 9, 1],
       [8, 5, 6]])

In [ ]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    print(s[i:i+3, j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= s[i:i+3, j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],     # Student 1
    [19, 92, 88],     # Student 2
    [17, 76, 95],     # Student 3
    [18, 65, 70],     # Student 4
    [20, 90, 85]])    # Student 5

In [ ]:
data.shape

(5, 3)

In [ ]:
np.mean(data[:,0])    #avg age of students

np.float64(18.4)

In [ ]:
data[:,1]      #extract maths marks

array([85, 92, 76, 65, 90])

In [ ]:
np.max(data[:,2])     #highest sci marks

np.int64(95)

In [ ]:
data[data[:,1] > 90]    #std who scored more than 90

array([[19, 92, 88]])

In [ ]:
d = data[:,1] + 5
d

array([90, 97, 81, 70, 95])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
len(data[data[:,0] < 19])

3

In [ ]:
np.mean(data[:,1:], axis = 0)

array([81.6, 83.2])

In [ ]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])