In [ ]:
#Array operations

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2

array([ 6,  7,  8,  9, 10])

In [ ]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [ ]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [ ]:
arr1 ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
#broadcasting

In [ ]:
import numpy as np

In [ ]:
l = [10, 20, 30, 40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [ ]:
arr + 10

array([20, 30, 40, 50])

In [ ]:
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#Deep and shallwcopy

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice= arr[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr
b = arr
b[0] = 11
b

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [6, 7]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [6, 7]])

In [ ]:
A @ B

array([[17, 20],
       [39, 46]])

In [ ]:
np.dot(A, B)

array([[17, 20],
       [39, 46]])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
#advance array manipulation

In [ ]:
import numpy as np

In [ ]:
#stacking array

In [ ]:
a= np.array([1, 2, 3, 4, 5])
b= np.array([6, 7, 8, 9, 10])      #stacking array
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.column_stack((a, b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
#Splitting array

In [ ]:
c= np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]